server:
  servlet:
    context-path: /chase
  port: 8080
#  tomcat:
#    threads:
#      max: 1
#      min-spare: 1
#    max-connections: 1
#    accept-count: 1
#    connection-timeout: 1000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/starry
    username: root
    password: south26@lite
  main:
    allow-circular-references: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: south26@lite
      database: 0
