server:
  servlet:
    context-path: /chase
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/starry
    username: root
    password: root

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
      database: 0
